### ISSUE TITLE
Program Stalling at 2% or 3% .

### ISSUE THREAD

**Issue by Isabel0715** [pawnsac/BLADE-deb#1]
Hi, I am writing to report an issue I have encountered while running this tool on my program. I have been experiencing a persistent problem where the program stalls at 2% or 3% progress during execution for more than 15 minutes. This issue occurs regardless of the number of cores used, ranging from 1 core to 14 cores.

I tried several times, here are two of the stack trace after forcefully terminating the program:
Stack trace 1:
```
  3%|██▎                                                                                        | 260/10371 [00:42<34:04,  4.95it/s][block with location:10111,13,10113,14 removed]

prev_removed:0 Down_traversal_activated: False

Process ForkPoolWorker-197:
Process ForkPoolWorker-198:
Traceback (most recent call last):
  File "/workspace/BLADE-deb/src/blade.py", line 124, in <module>
    main()
  File "/workspace/BLADE-deb/src/blade.py", line 104, in main
    reduction.reduction(token_map)
  File "/workspace/BLADE-deb/src/reduction.py", line 124, in reduction
    self.reduction(maps[nodes[loop_itr]])
  File "/workspace/BLADE-deb/src/reduction.py", line 124, in reduction
    self.reduction(maps[nodes[loop_itr]])
  File "/workspace/BLADE-deb/src/reduction.py", line 172, in reduction
    reduce_results = pool.map(self.reduce, pool_inputs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 768, in get
    self.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 765, in wait
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
KeyboardInterrupt
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 365, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
    self._event.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
KeyboardInterrupt
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt
Process ForkPoolWorker-199:
  3%|██▏                                                                                     | 260/10371 [16:38<10:47:06,  3.84s/it]
```
Stack trace 2:
```
  3%|██▎                                                                                        | 258/10231 [00:42<27:01,  6.15it/s][concat of 2 statements removed, location:9973,13,9978,14]

prev_removed:0 Down_traversal_activated: False
c^CProcess ForkPoolWorker-185:
Process ForkPoolWorker-186:
Traceback (most recent call last):
  File "blade.py", line 124, in <module>
    main()
  File "blade.py", line 104, in main
    reduction.reduction(token_map)
  File "/home/isabel0715/workspace/BLADE-new/src/reduction.py", line 124, in reduction
    self.reduction(maps[nodes[loop_itr]])
  File "/home/isabel0715/workspace/BLADE-new/src/reduction.py", line 124, in reduction
    self.reduction(maps[nodes[loop_itr]])
  File "/home/isabel0715/workspace/BLADE-new/src/reduction.py", line 171, in reduction
    reduce_results = pool.map(self.reduce, pool_inputs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
Process ForkPoolWorker-187:
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 765, in get
    self.wait(timeout)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 762, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
Traceback (most recent call last):
    waiter.acquire()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 356, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/isabel0715/workspace/BLADE-new/src/reduction.py", line 59, in reduce
    if run_test_case(f"./{self.oracle_cmd}", f"processing/{idx}/") == 0:
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/isabel0715/workspace/BLADE-new/src/process.py", line 9, in run_test_case
    stdout, stderr = process.communicate()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/usr/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1868, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
KeyboardInterrupt
  3%|██▏                                                                                     | 258/10231 [31:28<20:16:33,  7.32s/it]
```

It's worth mentioning that approximately two months ago, I was able to run the same program successfully using a similar and even more complex and time-consuming test.sh script. 

Apart from the stack trace, is there anything else that would be helpful for you to better understand and potentially reproduce the problem?

**Comment by Isabel0715** [comment]
Sorry, this seems to be a bug in my new script.
